// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PackedPolygon.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace g3.Proto {

  /// <summary>Holder for reflection information generated from PackedPolygon.proto</summary>
  public static partial class PackedPolygonReflection {

    #region Descriptor
    /// <summary>File descriptor for PackedPolygon.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PackedPolygonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNQYWNrZWRQb2x5Z29uLnByb3RvEghnMy5Qcm90byI7Cg5QYWNrZWRQb2x5",
            "Z29ucxIpCghQb2x5Z29ucxgBIAMoCzIXLmczLlByb3RvLlBhY2tlZFBvbHln",
            "b24iXQoNUGFja2VkUG9seWdvbhITCgtEZWx0YUNvb3JkcxgBIAMoERITCgtG",
            "bG9hdENvb3JkcxgCIAMoAhIPCgdVcFByb3BzGAMgASgEEhEKCURvd25Qcm9w",
            "cxgEIAEoBEILqgIIZzMuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::g3.Proto.PackedPolygons), global::g3.Proto.PackedPolygons.Parser, new[]{ "Polygons" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::g3.Proto.PackedPolygon), global::g3.Proto.PackedPolygon.Parser, new[]{ "DeltaCoords", "FloatCoords", "UpProps", "DownProps" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PackedPolygons : pb::IMessage<PackedPolygons>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PackedPolygons> _parser = new pb::MessageParser<PackedPolygons>(() => new PackedPolygons());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PackedPolygons> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::g3.Proto.PackedPolygonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PackedPolygons() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PackedPolygons(PackedPolygons other) : this() {
      polygons_ = other.polygons_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PackedPolygons Clone() {
      return new PackedPolygons(this);
    }

    /// <summary>Field number for the "Polygons" field.</summary>
    public const int PolygonsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::g3.Proto.PackedPolygon> _repeated_polygons_codec
        = pb::FieldCodec.ForMessage(10, global::g3.Proto.PackedPolygon.Parser);
    private readonly pbc::RepeatedField<global::g3.Proto.PackedPolygon> polygons_ = new pbc::RepeatedField<global::g3.Proto.PackedPolygon>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::g3.Proto.PackedPolygon> Polygons {
      get { return polygons_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PackedPolygons);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PackedPolygons other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!polygons_.Equals(other.polygons_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= polygons_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      polygons_.WriteTo(output, _repeated_polygons_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      polygons_.WriteTo(ref output, _repeated_polygons_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += polygons_.CalculateSize(_repeated_polygons_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PackedPolygons other) {
      if (other == null) {
        return;
      }
      polygons_.Add(other.polygons_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            polygons_.AddEntriesFrom(input, _repeated_polygons_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            polygons_.AddEntriesFrom(ref input, _repeated_polygons_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PackedPolygon : pb::IMessage<PackedPolygon>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PackedPolygon> _parser = new pb::MessageParser<PackedPolygon>(() => new PackedPolygon());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PackedPolygon> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::g3.Proto.PackedPolygonReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PackedPolygon() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PackedPolygon(PackedPolygon other) : this() {
      deltaCoords_ = other.deltaCoords_.Clone();
      floatCoords_ = other.floatCoords_.Clone();
      upProps_ = other.upProps_;
      downProps_ = other.downProps_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PackedPolygon Clone() {
      return new PackedPolygon(this);
    }

    /// <summary>Field number for the "DeltaCoords" field.</summary>
    public const int DeltaCoordsFieldNumber = 1;
    private static readonly pb::FieldCodec<int> _repeated_deltaCoords_codec
        = pb::FieldCodec.ForSInt32(10);
    private readonly pbc::RepeatedField<int> deltaCoords_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> DeltaCoords {
      get { return deltaCoords_; }
    }

    /// <summary>Field number for the "FloatCoords" field.</summary>
    public const int FloatCoordsFieldNumber = 2;
    private static readonly pb::FieldCodec<float> _repeated_floatCoords_codec
        = pb::FieldCodec.ForFloat(18);
    private readonly pbc::RepeatedField<float> floatCoords_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> FloatCoords {
      get { return floatCoords_; }
    }

    /// <summary>Field number for the "UpProps" field.</summary>
    public const int UpPropsFieldNumber = 3;
    private ulong upProps_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong UpProps {
      get { return upProps_; }
      set {
        upProps_ = value;
      }
    }

    /// <summary>Field number for the "DownProps" field.</summary>
    public const int DownPropsFieldNumber = 4;
    private ulong downProps_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong DownProps {
      get { return downProps_; }
      set {
        downProps_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PackedPolygon);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PackedPolygon other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!deltaCoords_.Equals(other.deltaCoords_)) return false;
      if(!floatCoords_.Equals(other.floatCoords_)) return false;
      if (UpProps != other.UpProps) return false;
      if (DownProps != other.DownProps) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= deltaCoords_.GetHashCode();
      hash ^= floatCoords_.GetHashCode();
      if (UpProps != 0UL) hash ^= UpProps.GetHashCode();
      if (DownProps != 0UL) hash ^= DownProps.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      deltaCoords_.WriteTo(output, _repeated_deltaCoords_codec);
      floatCoords_.WriteTo(output, _repeated_floatCoords_codec);
      if (UpProps != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(UpProps);
      }
      if (DownProps != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(DownProps);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      deltaCoords_.WriteTo(ref output, _repeated_deltaCoords_codec);
      floatCoords_.WriteTo(ref output, _repeated_floatCoords_codec);
      if (UpProps != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(UpProps);
      }
      if (DownProps != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(DownProps);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += deltaCoords_.CalculateSize(_repeated_deltaCoords_codec);
      size += floatCoords_.CalculateSize(_repeated_floatCoords_codec);
      if (UpProps != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UpProps);
      }
      if (DownProps != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(DownProps);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PackedPolygon other) {
      if (other == null) {
        return;
      }
      deltaCoords_.Add(other.deltaCoords_);
      floatCoords_.Add(other.floatCoords_);
      if (other.UpProps != 0UL) {
        UpProps = other.UpProps;
      }
      if (other.DownProps != 0UL) {
        DownProps = other.DownProps;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            deltaCoords_.AddEntriesFrom(input, _repeated_deltaCoords_codec);
            break;
          }
          case 18:
          case 21: {
            floatCoords_.AddEntriesFrom(input, _repeated_floatCoords_codec);
            break;
          }
          case 24: {
            UpProps = input.ReadUInt64();
            break;
          }
          case 32: {
            DownProps = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            deltaCoords_.AddEntriesFrom(ref input, _repeated_deltaCoords_codec);
            break;
          }
          case 18:
          case 21: {
            floatCoords_.AddEntriesFrom(ref input, _repeated_floatCoords_codec);
            break;
          }
          case 24: {
            UpProps = input.ReadUInt64();
            break;
          }
          case 32: {
            DownProps = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
